export const FETCH_USERS = 'FETCH_USERS';
export const CREATE_USER = 'CREATE_USER';

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const FETCH_LOGIN_STATUS = 'FETCH_LOGIN_STATUS';

export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const CREATE_COMPANY = 'CREATE_COMPANY';

export const CREATE_ALLOWLIST_EMAIL = 'CREATE_ALLOWLIST_EMAIL';
export const CREATE_ALLOWLIST_DOMAIN = 'CREATE_ALLOWLIST_DOMAIN';
export const DELETE_ALLOWLIST_EMAIL = 'DELETE_ALLOWLIST_EMAIL'
export const DELETE_ALLOWLIST_DOMAIN = 'DELETE_ALLOWLIST_DOMAIN';
